### ISSUE TITLE
Difference between train.py and train_with_func.py

### ISSUE THREAD

**Issue by zhtmike** [mindspore-lab/mindcv#251]
Hi, may I know if `train.py` and `train_with_func.py` functions same? Under which situation we should use `train_with_func.py` instead of `train.py`? I see `train_with_func.py` has more than 200 lines of codes compared with the default one. Much thanks!

**Comment by SamitHuang** [comment]
Sorry for the late reply. train_with_func.py uses grad_and_value()  to do the train step while train.py uses model.train(). train_with_func.py is experimental currently and will be improved after MindSpore 2.0 released.

**Comment by zhtmike** [comment]
Thanks!
