### ISSUE TITLE
运行test_parallel_train_val.py脚本报错

### ISSUE THREAD

**Issue by Venomfly** [mindspore-lab/mindcv#299]
涉及的URL：https://github.com/mindspore-lab/mindcv/tree/main/tests

To test training in distributed mode if you have multiple GPUs:
运行如下脚本报错：（转换成浮点数失败）
pytest tests/tasks/parallel/test_parallel_train_val.py
![image](https://user-images.githubusercontent.com/99794814/208425839-d2d6e2f1-109e-495f-aaf1-96d7f58e560b.png)

**Comment by SamitHuang** [comment]
solved in https://github.com/mindspore-lab/mindcv/pull/301

**Comment by geniuspatrick** [comment]
is the bug fixed? Can we close this issue?
