### ISSUE TITLE
模型推理结果与预期不一致（Inference.md）

### ISSUE THREAD

**Issue by Venomfly** [mindspore-lab/mindcv#300]
涉及的URL：https://github.com/mindspore-lab/mindcv/blob/main/tutorials/Inference.md
根据资料中步骤进行模型推理如下图，实测得到最后结果为 predict: matchstick，与预期结果不一致。
![image](https://user-images.githubusercontent.com/99794814/208578234-e6e28325-883a-46b5-9d91-c2aa47356840.png)

**Comment by Songyuanwei** [comment]
fixed in PR  https://github.com/mindspore-lab/mindcv/pull/305
