### ISSUE TITLE
Incorrect model weight urls for PoolFormer

### ISSUE THREAD

**Issue by SamitHuang** [mindspore-lab/mindcv#322]
链接文件不是ckpt，且跟其他模型存放的server不一样。
 37 default_cfgs = dict(
 38     poolformer_s12=_cfg(
 39         url='https://github.com/sail-sg/poolformer/releases/download/v1.0/poolformer_s12.pth.tar',
 40         crop_pct=0.9),
 41     poolformer_s24=_cfg(
 42         url='https://github.com/sail-sg/poolformer/releases/download/v1.0/poolformer_s24.pth.tar',
 43         crop_pct=0.9),
 44     poolformer_s36=_cfg(
 45         url='https://github.com/sail-sg/poolformer/releases/download/v1.0/poolformer_s36.pth.tar',
 46         crop_pct=0.9),
 47     poolformer_m36=_cfg(
 48         url='https://github.com/sail-sg/poolformer/releases/download/v1.0/poolformer_m36.pth.tar',
 49         crop_pct=0.95),
 50     poolformer_m48=_cfg(
 51         url='https://github.com/sail-sg/poolformer/releases/download/v1.0/poolformer_m48.pth.tar',
 52         crop_pct=0.95),
 53 )
 54

**Comment by geniuspatrick** [comment]
fixed in #339
