### ISSUE TITLE
Failed to execute training

### ISSUE THREAD

**Issue by Venomfly** [mindspore-lab/mindcv#329]
涉及的URL：https://github.com/mindspore-lab/mindcv/tree/main/configs/convit
执行如下训练命令失败，改为mpirun -n 8 可正常启动训练
# train convit_tiny on 8 Ascends
python train.py --config configs/convit/convit_tiny_ascend.yaml --data_dir /path/to/imagenet

**Comment by geniuspatrick** [comment]
duplicate issue of #335 , we will disscuss it in #335 . Closed.
