### ISSUE TITLE
[MODEL] [PVT] Failed to execute training command

### ISSUE THREAD

**Issue by Venomfly** [mindspore-lab/mindcv#341]
涉及的URL：https://github.com/mindspore-lab/mindcv/tree/main/configs/pvt
执行如下训练脚本报错：TypeError: Select GPU operator[FusedWeightApplyMomentum] fail! Unsupported data type!
![image](https://user-images.githubusercontent.com/99794814/209621564-d0552957-4ac7-463a-a962-3921bfbeefff.png)

**Comment by geniuspatrick** [comment]
@The-truthh, Please fix this issue as we discussed yesterday.
