### ISSUE TITLE
mindcv/configs/repmlp/目录下未找到启动训练的shell脚本和json文件

### ISSUE THREAD

**Issue by Venomfly** [mindspore-lab/mindcv#342]
涉及的URL：https://github.com/mindspore-lab/mindcv/tree/main/configs/repmlp
mindcv/configs/repmlp/目录下未找到启动训练的shell脚本和json文件，请补充
![image](https://user-images.githubusercontent.com/99794814/209623532-6e8245ea-fc1e-426c-b68a-6b2aa7427863.png)

**Comment by geniuspatrick** [comment]
duplicate issue of #335 , we will disscuss it in #335 . Closed.
