### ISSUE TITLE
mindcv/configs/rexnet/ 下  所有yaml文件命名不规范，少了_gpu或者_ascend的后缀

### ISSUE THREAD

**Issue by tacyi** [mindspore-lab/mindcv#497]
If this is your first time, please read our contributor guidelines:
https://github.com/mindspore-lab/mindcv/blob/main/CONTRIBUTING.md

**Describe the bug/ 问题描述 (Mandatory / 必填)**
mindcv/configs/rexnet/ 下  所有yaml文件命名不规范，少了_gpu或者_ascend的后缀

- **Hardware Environment(`Ascend`/`GPU`/`CPU`)  / 硬件环境**:
> Please delete the backend not involved / 请删除不涉及的后端:
> /device ascend/GPU/CPU/kirin/等其他芯片

- **Software Environment / 软件环境 (Mandatory / 必填)**:
-- MindSpore version (e.g., 1.7.0.Bxxx) :
-- Python version (e.g., Python 3.7.5) :
-- OS platform and distribution (e.g., Linux Ubuntu 16.04):
-- GCC/Compiler version (if compiled from source):

- **Excute Mode / 执行模式 (Mandatory / 必填)(`PyNative`/`Graph`)**:
> Please delete the mode not involved / 请删除不涉及的模式:
> /mode pynative
> /mode graph

**To Reproduce / 重现步骤 (Mandatory / 必填)**

**Expected behavior / 预期结果 (Mandatory / 必填)**

**Screenshots/ 日志 / 截图 (Mandatory / 必填)**

**Additional context / 备注 (Optional / 选填)**

**Comment by YUANMU227** [comment]
你好，这个如何设置，选择使用gpu和ascend呢，我看很多config，后缀有gpu和ascend，其实内容都一样

**Comment by Songyuanwei** [comment]
fixed on https://github.com/mindspore-lab/mindcv/pull/544

**Comment by tacyi** [comment]
已确认关联的解单号内容正确，关闭问题单
