### ISSUE TITLE
请问mindcv可以使用tensorboard吗，使用方法是什么

### ISSUE THREAD

**Issue by YUANMU227** [mindspore-lab/mindcv#501]
If this is your first time, please read our contributor guidelines: https://gitee.com/mindspore/mindspore/blob/master/CONTRIBUTING.md

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Songyuanwei** [comment]
参考mindinsight https://www.mindspore.cn/mindinsight/docs/zh-CN/r2.0.0-alpha/index.html

**Comment by YUANMU227** [comment]
> 

感谢
