### ISSUE TITLE
mobilenet_v1_1_0网络规格readme上的top1,top5精度值，与提供的对应的权重文件差距较大

### ISSUE THREAD

**Issue by tacyi** [mindspore-lab/mindcv#537]
**Describe the bug/ 问题描述 (Mandatory / 必填)**
转验时mobilenet_v1_1_0网络规格readme上的top1,top5精度值，与提供的对应的权重文件差距较大
刚刚咨询了开发，开发说现在readme上的top1,top5精度值有更新

- **Hardware Environment(`Ascend`/`GPU`/`CPU`)  / 硬件环境**:
> Please delete the backend not involved / 请删除不涉及的后端:
/device GPU

- **Software Environment / 软件环境 (Mandatory / 必填)**:
-- MindSpore version (e.g., 1.7.0.Bxxx) :commit_id = ''[sha1]:c69cc34d,[branch]:(HEAD,origin/r1.8,r1.8)'' Version: 1.8.1
-- Python version (e.g., Python 3.7.5) :Python 3.7.5
-- OS platform and distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
-- GCC/Compiler version (if compiled from source):gcc version 7.3.0 (GCC)

- **Excute Mode / 执行模式 (Mandatory / 必填)(`PyNative`/`Graph`)**:
> Please delete the mode not involved / 请删除不涉及的模式:
/mode graph

**To Reproduce / 重现步骤 (Mandatory / 必填)**
无需复现，因为现在的readme精度已被更新
python /data/jenkins/workspace/Kits_Version_Deploy_GPU_Ubuntu_x86/mindcv/validate.py -c /data/jenkins/workspace/Kits_Version_Deploy_GPU_Ubuntu_x86/mindcv/configs/mobilenetv1/mobilenet_v1_1.0_gpu.yaml --data_dir /nfs_for_sync/Mindlab_data/dataset/ImageNet_Original/ --ckpt_path /nfs_for_sync/Mindlab_data/mindcv_models_ckpt/r1_8_1/mobilenetv1/mobilenet_v1_100_224-200_2502.ckpt > case.log 2>&1 

**Expected behavior / 预期结果 (Mandatory / 必填)**
正常是以转验时的那版资料已经写好用例，所以是针对资料版本提的问题单

**Screenshots/ 日志 / 截图 (Mandatory / 必填)**

**Additional context / 备注 (Optional / 选填)**

**Comment by Songyuanwei** [comment]
fixed on #533

**Comment by tacyi** [comment]
已确认关联的解单号内容正确，关闭问题单
