### ISSUE TITLE
resnet_101_gpu网络规格readme上的top1，与提供的对应的权重文件差距较大，实际看护的top1<readme 上的top1-0.5

### ISSUE THREAD

**Issue by tacyi** [mindspore-lab/mindcv#539]
Describe the bug/ 问题描述 (Mandatory / 必填)
转验时resnet_101_gpu网络规格readme上的top1精度值，与提供的对应的权重文件差距较大

Hardware Environment(Ascend/GPU/CPU) / 硬件环境:
Please delete the backend not involved / 请删除不涉及的后端:
/device GPU

Software Environment / 软件环境 (Mandatory / 必填):
-- MindSpore version (e.g., 1.7.0.Bxxx) :commit_id = ''[sha1]:c69cc34d,[branch]:(HEAD,origin/r1.8,r1.8)'' Version: 1.8.1
-- Python version (e.g., Python 3.7.5) :Python 3.7.5
-- OS platform and distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
-- GCC/Compiler version (if compiled from source):gcc version 7.3.0 (GCC)

Excute Mode / 执行模式 (Mandatory / 必填)(PyNative/Graph):

Please delete the mode not involved / 请删除不涉及的模式:
/mode graph

To Reproduce / 重现步骤 (Mandatory / 必填)
python /data/jenkins/workspace/Kits_Version_Deploy_GPU_Ubuntu_x86/mindcv/validate.py -c /data/jenkins/workspace/Kits_Version_Deploy_GPU_Ubuntu_x86/mindcv/configs/resnet/resnet_101_gpu.yaml --data_dir /nfs_for_sync/Mindlab_data/dataset/ImageNet_Original/ --ckpt_path /nfs_for_sync/Mindlab_data/mindcv_models_ckpt/r1_8_1/resnet/resnet101_224.ckpt > case.log 2>&1 

Expected behavior / 预期结果 (Mandatory / 必填)
目前定的精度范围是[readme 上的top1-0.5, readme 上的top1+0.5]

Screenshots/ 日志 / 截图 (Mandatory / 必填)

Additional context / 备注 (Optional / 选填)

**Comment by Songyuanwei** [comment]
fixed on #548

**Comment by tacyi** [comment]
已确认关联的解单号内容正确，关闭问题单
