### ISSUE TITLE
[regnet] [Ascend910]  Regnet needs to supplement the default values in the configuration file

### ISSUE THREAD

**Issue by 787918582** [mindspore-lab/mindcv#559]
If this is your first time, please read our contributor guidelines:
https://github.com/mindspore-lab/mindcv/blob/main/CONTRIBUTING.md

**Describe the bug/ 问题描述 (Mandatory / 必填)**
在执行rexnet的训练和推理时均报相同错误，定位原因发现是配置文件中‘model’的默认值为空，参考了mindcv下的其他网络配置文件的格式，建议补充regnet模型配置文件中'model'的默认值

- **Hardware Environment(`Ascend`/`GPU`/`CPU`)  / 硬件环境**:
> Please delete the backend not involved / 请删除不涉及的后端:
> /device ascend/GPU

- **Software Environment / 软件环境 (Mandatory / 必填)**:
-- MindSpore version (e.g., 1.7.0.Bxxx) :commit_id = ''[sha1]:c69cc34d,[branch]:(HEAD,origin/r1.8,r1.8)''
-- Python version (e.g., Python 3.7.5) :3.7.5
-- OS platform and distribution (e.g., Linux Ubuntu 16.04):EulerOS2.8
-- GCC/Compiler version (if compiled from source):7.3.0

- **Excute Mode / 执行模式 (Mandatory / 必填)(`PyNative`/`Graph`)**:
> Please delete the mode not involved / 请删除不涉及的模式:
> /mode pynative
> /mode graph

**To Reproduce / 重现步骤 (Mandatory / 必填)**
1. mpirun --allow-run-as-root -n 8 python train.py --config configs/regnet/regnet_x_800mf_ascend.yaml --distribute True --data_dir /ImageNet_Origin/

**Expected behavior / 预期结果 (Mandatory / 必填)**
希望可以设置好配置文件中'model'的默认值

**Screenshots/ 日志 / 截图 (Mandatory / 必填)**
1. 报错截图
![rexnet_1](https://user-images.githubusercontent.com/76412544/226549180-02f7ef4e-8924-4696-a061-3fcd77d47ae6.png)
2. regnet配置文件中model的默认值截图
![rexnet_2](https://user-images.githubusercontent.com/76412544/226549275-26567890-42f4-43ea-85dd-6bb85bbfff17.png)
3. 参考mindcv下其他模型的格式，model存在默认值
![rexnet_3](https://user-images.githubusercontent.com/76412544/226549397-05cef6bd-8cde-48fb-8874-6bef8fad0374.png)

**Additional context / 备注 (Optional / 选填)**
mindcv_version：https://repo.mindspore.cn/mindspore-lab/MindCV/daily/202303/20230310/main_20230310001230_ef24818546b9e2d3abb4dd78b2b9da57611da0d1/
mindcv_source_code: 2023.03.13

**Comment by Songyuanwei** [comment]
configs/rexnet/rexnet_x09_ascend.yaml 是有model参数的

**Comment by 787918582** [comment]
经验证，已修复
