### ISSUE TITLE
Support for MindSpore 2.0

### ISSUE THREAD

**Issue by SamitHuang** [mindspore-lab/mindcv#565]
If this is your first time, please read our contributor guidelines: https://gitee.com/mindspore/mindspore/blob/master/CONTRIBUTING.md

**Is your feature request related to a problem? Please describe.**

Training and evaluation fails on MS 2.0. Need fix.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by geniuspatrick** [comment]
solved in #674
