### ISSUE TITLE
Quick test on history training recipe compatibility for update.

### ISSUE THREAD

**Issue by SamitHuang** [mindspore-lab/mindcv#566]
If this is your first time, please read our contributor guidelines: https://gitee.com/mindspore/mindspore/blob/master/CONTRIBUTING.md

**Is your feature request related to a problem? Please describe.**

Some args in yaml config will mismatch the latest code. We need to verify it for a CI.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by geniuspatrick** [comment]
fixed in #574
