### ISSUE TITLE
[edgenext] [Ascend910] [GRAPH] There is a problem with the validate logic

### ISSUE THREAD

**Issue by 787918582** [mindspore-lab/mindcv#607]
If this is your first time, please read our contributor guidelines:
https://github.com/mindspore-lab/mindcv/blob/main/CONTRIBUTING.md

**Describe the bug/ 问题描述 (Mandatory / 必填)**
edgenext进行推理，当传入错误ckpt地址时并不报错，且仍继续进行推理，最终推理出的精度不达标

- **Hardware Environment(`Ascend`/`GPU`/`CPU`)  / 硬件环境**:
> Please delete the backend not involved / 请删除不涉及的后端:
> /device ascend

- **Software Environment / 软件环境 (Mandatory / 必填)**:
-- MindSpore version (e.g., 1.7.0.Bxxx) :commit_id = ''[sha1]:c69cc34d,[branch]:(HEAD,origin/r1.8,r1.8)''
-- Python version (e.g., Python 3.7.5) :3.7.5
-- OS platform and distribution (e.g., Linux Ubuntu 16.04):EulerOS2.8
-- GCC/Compiler version (if compiled from source):7.3.0

- **Excute Mode / 执行模式 (Mandatory / 必填)(`PyNative`/`Graph`)**:
> Please delete the mode not involved / 请删除不涉及的模式:
> /mode graph

**To Reproduce / 重现步骤 (Mandatory / 必填)**
1. python validate.py   /data1/jenkins/workspace/Kits_Version_Deploy_Ascend_Linux_mindcv/mindcv_models_test_data/test_edgenext_base_ascend/test_val_edgenext_base_ascend_imagenet2012_graph_1p_001/edgenext_base_ascend.yaml --data_dir /nfs_for_sync/Mindlab_data/dataset/ImageNet_Original --ckpt_path /nfs_for_sync/Mindlab_data/mindcv_models_ckpt/r1_8_1/edgenext/edgenext_base-4335e9dc.ckpt --mode 0 > eval.log 2>&1

**Expected behavior / 预期结果 (Mandatory / 必填)**
若传入的地址有问题，能正常报错

**Screenshots/ 日志 / 截图 (Mandatory / 必填)**
1. ckpt文件不存在
![edgenext_1](https://user-images.githubusercontent.com/76412544/232698153-9f754daf-fd4a-42e1-b758-217e5ce8293d.png)
2. 推理出的精度
![edgenext_2](https://user-images.githubusercontent.com/76412544/232698221-122a4f0a-2271-4b7e-a46f-d4f1b38b8204.png)

**Additional context / 备注 (Optional / 选填)**

**Comment by geniuspatrick** [comment]
duplicated of #610
