### ISSUE TITLE
[poolformer_s12] [Ascend910] [GRAPH] The inference precision of the weight file does not meet the requirement

### ISSUE THREAD

**Issue by 787918582** [mindspore-lab/mindcv#614]
If this is your first time, please read our contributor guidelines:
https://github.com/mindspore-lab/mindcv/blob/main/CONTRIBUTING.md

**Describe the bug/ 问题描述 (Mandatory / 必填)**
poolformer_s12 使用readme提供的权重文件进行推理：https://download.mindspore.cn/toolkits/mindcv/poolformer/poolformer_s12-5be5c4e4.ckpt
开发提供的精度标准为：77.33%
测试实测精度：{'Top_1_Accuracy': 0.75508, 'Top_5_Accuracy': 0.92488, 'loss': 1.9488102343678475}
精度差距1.82%

- **Hardware Environment(`Ascend`/`GPU`/`CPU`)  / 硬件环境**:
> Please delete the backend not involved / 请删除不涉及的后端:
> /device ascend

- **Software Environment / 软件环境 (Mandatory / 必填)**:
-- MindSpore version (e.g., 1.7.0.Bxxx) :commit_id = ''[sha1]:c69cc34d,[branch]:(HEAD,origin/r1.8,r1.8)''
-- Python version (e.g., Python 3.7.5) :3.7.5
-- OS platform and distribution (e.g., Linux Ubuntu 16.04):EulerOS2.8
-- GCC/Compiler version (if compiled from source):7.3.0

- **Excute Mode / 执行模式 (Mandatory / 必填)(`PyNative`/`Graph`)**:
> Please delete the mode not involved / 请删除不涉及的模式:
> /mode graph

**To Reproduce / 重现步骤 (Mandatory / 必填)**
1. python validate.py --config ./configs/sknet/skresnet18_ascend.yaml   --data_dir ./data --ckpt_path ./sknet18-868228e5.ckpt --mode 0

**Expected behavior / 预期结果 (Mandatory / 必填)**
复现标准精度

**Screenshots/ 日志 / 截图 (Mandatory / 必填)**
{'Top_1_Accuracy': 0.75508, 'Top_5_Accuracy': 0.92488, 'loss': 1.9488102343678475}

**Additional context / 备注 (Optional / 选填)**
mindcv_version：2023.04.23
mindcv_source_code: 2023.04.23

**Comment by geniuspatrick** [comment]
We have a notation in the [readme](https://github.com/mindspore-lab/mindcv/tree/main/configs/poolformer#validation) of poolformer
