### ISSUE TITLE
新增学习率调整策略：Cyclic、OneCycle，并在部分网络上验证效果

### ISSUE THREAD

**Issue by XixinYang** [mindspore-lab/mindcv#625]
If this is your first time, please read our contributor guidelines: https://gitee.com/mindspore/mindspore/blob/master/CONTRIBUTING.md

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by geniuspatrick** [comment]
solved in #657
