### ISSUE TITLE
requirements.txt文档中依赖包不全

### ISSUE THREAD

**Issue by Venomfly** [mindspore-lab/mindcv#647]
1. 【Document Link】/【文档链接】
https://github.com/mindspore-lab/mindcv/tree/main
2. 【Issues Section】/【问题文档片段】
pip install -r requirements.txt
3. 【Existing Issues】/【存在的问题】
requirements.txt里面只涉及了（numpy>=1.17.0，pyyaml>=5.3，tqdm）依赖，缺少（mindspore >= 1.8.1openmpi 4.0.3 )，请补充全部的依赖包在requirements.txt
4. 【Expected Result】【预期结果】
所有依赖包均在requirements.txt，

**Comment by geniuspatrick** [comment]
Nope. `requirements.txt`
