### ISSUE TITLE
with_func实验性质的脚本不稳定，需加上备注。

### ISSUE THREAD

**Issue by Venomfly** [mindspore-lab/mindcv#648]
1. 【Document Link】/【文档链接】
https://github.com/mindspore-lab/mindcv/tree/main/examples
2. 【Issues Section】/【问题文档片段】
mpirun --allow-run-as-root -n 4 python examples/train_parallel_with_func_example.py
3. 【Existing Issues】/【存在的问题】
运行该命令报错：
ImportError: cannot import name 'Allreduce' from 'mindcv.utils' (/data2/rhx/mindcv/src/mindcv/mindcv/utils/__init__.py)

**Comment by geniuspatrick** [comment]
It'a already in our repo [readme](https://github.com/mindspore-lab/mindcv/blob/main/README.md?plain=1#L166) and docs [homepage](https://mindspore-lab.github.io/mindcv/#training) (There's even a prominent tooltip here).
