### ISSUE TITLE
.md文件未完成全英文说明

### ISSUE THREAD

**Issue by Venomfly** [mindspore-lab/mindcv#649]
1. 【Document Link】/【文档链接】
https://github.com/mindspore-lab/mindcv/blob/main/tutorials/finetune.md
https://github.com/mindspore-lab/mindcv/blob/main/tutorials/inference.md
https://github.com/mindspore-lab/mindcv/blob/main/tutorials/learn_about_config.md
2. 【Issues Section】/【问题文档片段】
下载Notebook
3. 【Existing Issues】/【存在的问题】
下载Notebook    应该为全英文

**Comment by geniuspatrick** [comment]
fixed in #665
