### ISSUE TITLE
RELEASE.md中未使用最新的包版本的说明

### ISSUE THREAD

**Issue by Venomfly** [mindspore-lab/mindcv#653]
1. 【Document Link】/【文档链接】
https://github.com/mindspore-lab/mindcv/blob/main/RELEASE.md
2. 【Issues Section】/【问题文档片段】
该readme里面的内容包版本需要更新
3. 【Existing Issues】/【存在的问题】
RELEASE.md中内容涉及包版本，未使用最新的说明。

**Comment by geniuspatrick** [comment]
fixed in #669
