### ISSUE TITLE
swin_transformer.py中的SwinTransformer使用nn.CellList.append导致parameters_and_names()返回的name和parameter.name不一致

### ISSUE THREAD

**Issue by wuzhf9** [mindspore-lab/mindcv#683]
If this is your first time, please read our contributor guidelines:
https://github.com/mindspore-lab/mindcv/blob/main/CONTRIBUTING.md

**Describe the bug/ 问题描述 (Mandatory / 必填)**
swin_transformer.py中的SwinTransformer使用nn.CellList.append导致parameters_and_names()返回的name和parameter.name不一致

- **Hardware Environment(`Ascend`/`GPU`/`CPU`)  / 硬件环境**:
Ascend/GPU/CPU

- **Software Environment / 软件环境 (Mandatory / 必填)**:
MindSpore1.8.1

- **Excute Mode / 执行模式 (Mandatory / 必填)(`PyNative`/`Graph`)**:
graph/pynative

**To Reproduce / 重现步骤 (Mandatory / 必填)**
```python
from mindcv.models import create_model

model = create_model(model_name="swin_tiny")
for name, param in model.parameters_and_names():
    print(name, param.name)
```
输出的name和param.name不一致。
但是使用SwinTransformer作为基类的模型则不会出现该参数名称不一致的问题，这会导致以SwinTransformer作为backbone的预训练模型，例如Simmim，在预训练完成之后，由于参数名称不一致的问题无法将参数加载到SwinTransformer中进行微调。

经过排查发现该问题是由于使用了nn.CellList.append方法导致，将swin_transformer.py中第636~650行的代码作如下改动即可避免：
```python
    self.layers = nn.CellList([
        layer = BasicLayer(
            dim=int(embed_dim * 2 ** i_layer),
            input_resolution=(patches_resolution[0] // (2 ** i_layer),
                              patches_resolution[1] // (2 ** i_layer)),
            depth=depths[i_layer],
            num_heads=num_heads[i_layer],
            window_size=window_size,
            mlp_ratio=self.mlp_ratio,
            qkv_bias=qkv_bias, qk_scale=qk_scale,
            drop=drop_rate, attn_drop=attn_drop_rate,
            drop_path=dpr[sum(depths[:i_layer]):sum(depths[:i_layer + 1])],
            norm_layer=norm_layer,
            downsample=PatchMerging if (i_layer < self.num_layers - 1) else None
        ) for i_layer in range(self.num_layers)
    ])
```
**Expected behavior / 预期结果 (Mandatory / 必填)**
使用parameters_and_names()返回的name和parameter.name一致。

**Screenshots/ 日志 / 截图 (Mandatory / 必填)**
![image](https://github.com/mindspore-lab/mindcv/assets/66479934/12cefede-e5ee-469e-9d16-8761152de840)

**Additional context / 备注 (Optional / 选填)**
经排查MindCV仓中还有以下模型使用了nn.CellList.append()，可能会出现相同的问题。
coat: 
https://github.com/mindspore-lab/mindcv/blob/main/mindcv/models/coat.py#L115
convnext: 
https://github.com/mindspore-lab/mindcv/blob/main/mindcv/models/convnext.py#L190
https://github.com/mindspore-lab/mindcv/blob/main/mindcv/models/convnext.py#L196
https://github.com/mindspore-lab/mindcv/blob/main/mindcv/models/convnext.py#L207
crossvit:
https://github.com/mindspore-lab/mindcv/blob/main/mindcv/models/crossvit.py#L363
densenet:
https://github.com/mindspore-lab/mindcv/blob/main/mindcv/models/densenet.py#L94
edgenext:
https://github.com/mindspore-lab/mindcv/blob/main/mindcv/models/edgenext.py#L334
https://github.com/mindspore-lab/mindcv/blob/main/mindcv/models/edgenext.py#L360
mixnet:
https://github.com/mindspore-lab/mindcv/blob/main/mindcv/models/mixnet.py#L92
https://github.com/mindspore-lab/mindcv/blob/main/mindcv/models/mixnet.py#L141
nasnet:
https://github.com/mindspore-lab/mindcv/blob/main/mindcv/models/nasnet.py#L249
https://github.com/mindspore-lab/mindcv/blob/main/mindcv/models/nasnet.py#L369
pit:
https://github.com/mindspore-lab/mindcv/blob/main/mindcv/models/pit.py#L318-L319
pnasnet:
https://github.com/mindspore-lab/mindcv/blob/main/mindcv/models/pnasnet.py#L187-L195
regnet:
https://github.com/mindspore-lab/mindcv/blob/main/mindcv/models/regnet.py#L296-L300
https://github.com/mindspore-lab/mindcv/blob/main/mindcv/models/regnet.py#L385-L389
res2net:
https://github.com/mindspore-lab/mindcv/blob/main/mindcv/models/res2net.py#L81-L85
swin_transformer:
https://github.com/mindspore-lab/mindcv/blob/main/mindcv/models/swin_transformer.py#L636-L650

**Comment by IASZHT** [comment]
Thank you for your contribution to mindcv. We will modify the above network that calls the nn.CellList.append function. The pull-requests link will be attached later.
