### ISSUE TITLE
mindcv导入后报错

### ISSUE THREAD

**Issue by thzva** [mindspore-lab/mindcv#692]
第一次提问链接为：https://gitee.com/mindspore/docs/issues/I7DPAP#note_18903499

在Ascend910服务器上使用"all-in-one"docker，版本为“23.0.RC1”（镜像更新时间为2023-05-23 14:29:07）。

pip install mindcv成功

在使用python命令import mindcv时候出现如下报错

Traceback (most recent call last):

File "", line 1, in

File "/usr/local/python3.7.5/lib/python3.7/site-packages/mindcv/init.py", line 2, in

from . import data, loss, models, optim, scheduler, utils
File "/usr/local/python3.7.5/lib/python3.7/site-packages/mindcv/optim/init.py", line 2, in

from . import optim_factory
File "/usr/local/python3.7.5/lib/python3.7/site-packages/mindcv/optim/optim_factory.py", line 7, in

from .adamw import AdamW
File "/usr/local/python3.7.5/lib/python3.7/site-packages/mindcv/optim/adamw.py", line 7, in

from mindspore._checkparam import Rel
ImportError: cannot import name 'Rel' from 'mindspore._checkparam' (/usr/local/python3.7.5/lib/python3.7/site-packages/mindspore/_checkparam.py)

**Comment by geniuspatrick** [comment]
hi, it seems that you are using a outdated version of mindcv, try to upgrade to the latest version:
```shell
pip install -U mindcv
```
and enjoy!

**Comment by thzva** [comment]
> hi, it seems that you are using a outdated version of mindcv, try to upgrade to the latest version:
> 
> ```shell
> pip install -U mindcv
> ```
> 
> and enjoy!

Sorry, the issuse is still exist.

**Comment by geniuspatrick** [comment]
run

```shell
cat /usr/local/python3.7.5/lib/python3.7/site-packages/mindcv/version.py
```

what do you get?

**Comment by thzva** [comment]
We can solve the problem by using this code: pip install mindcv -i https://pypi.tuna.tsinghua.edu.cn/simple
the issue caused that the docker uses Douban Source, but Douban did not updated mindcv to 0.2.2

**Comment by geniuspatrick** [comment]
Thank you for reporting this.
