### ISSUE TITLE
resnet50 val_while_train 报错

### ISSUE THREAD

**Issue by AspartameJ** [mindspore-lab/mindcv#723]
If this is your first time, please read our contributor guidelines:
https://github.com/mindspore-lab/mindcv/blob/main/CONTRIBUTING.md

**Describe the bug/ 问题描述 (Mandatory / 必填)**
> 在openi上使用train.py脚本在cifar10上训练resnet50的时候，启用--val_while_train True参数报错，报错提示没有val这个usage。  

- **Hardware Environment(`Ascend`/`GPU`/`CPU`)  / 硬件环境**:
> Please delete the backend not involved / 请删除不涉及的后端:
> /device ascend

- **Software Environment / 软件环境 (Mandatory / 必填)**:
-- MindSpore version (e.g., 1.7.0.Bxxx) : 1.10.1
-- Python version (e.g., Python 3.7.5) : 3.7.10
-- OS platform and distribution (e.g., Linux Ubuntu 16.04): EulerOS 2.0 (SP8)
-- GCC/Compiler version (if compiled from source):

- **Excute Mode / 执行模式 (Mandatory / 必填)(`PyNative`/`Graph`)**:
> Please delete the mode not involved / 请删除不涉及的模式:
> /mode graph

**To Reproduce / 重现步骤 (Mandatory / 必填)**
1. git clone https://github.com/mindspore-lab/mindcv.git  
2. 进入mindcv目录  
3. pip install -e .
4. 下载cifar10数据集到cifar-10-batches-bin  
5. python train.py --model resnet50 --dataset cifar10 --data_dir ./cifar-10-batches-bin  --batch_size 128 --val_while_train True
6. See error

**Expected behavior / 预期结果 (Mandatory / 必填)**
```shell
(MindSpore) [ma-user mindcv]$python train.py --model resnet50 --dataset cifar10 --data_dir ./cifar-10-batches-bin  --batch_size 128 --val_while_train True
Traceback (most recent call last):
  File "train.py", line 337, in <module>
    train(args)
  File "train.py", line 124, in train
    download=args.dataset_download,
  File "/home/ma-user/work/mindcv/mindcv/data/dataset_factory.py", line 152, in create_dataset
    **mindspore_kwargs,
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/dataset/engine/validators.py", line 351, in new_method
    check_valid_str(usage, ["train", "test", "all"], "usage")
  File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/dataset/core/validator_helpers.py", line 405, in check_valid_str
    raise ValueError("Input {0} is not within the valid set of {1}.".format(arg_name, str(valid_strings)))
ValueError: Input usage is not within the valid set of ['train', 'test', 'all'].
```

**Screenshots/ 日志 / 截图 (Mandatory / 必填)**
![image](https://github.com/mindspore-lab/mindcv/assets/50703165/5be37930-99f7-476f-adfb-20f65f99c1be)

**Additional context / 备注 (Optional / 选填)**

**Comment by geniuspatrick** [comment]
`cifar10` only have 2 subset `train` and `test`. You need to pass `--val_split=test` to `train.py`
