### ISSUE TITLE
mindcv quick start  中报错   Could not load library libcudnn_cnn_infer.so.8. Error: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libnvrtc.so: undefined symbol: nvrtcGetCUBIN

### ISSUE THREAD

**Issue by yyl-cloud** [mindspore-lab/mindcv#729]
mindcv quick start  中报错   Could not load library libcudnn_cnn_infer.so.8. Error: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libnvrtc.so: undefined symbol: nvrtcGetCUBIN

**Comment by geniuspatrick** [comment]
Can you check if `mindspore` is successfully installed by:
```shell
python -c "import mindspore;mindspore.set_context(device_target='GPU');mindspore.run_check()"
```
Please refer to https://www.mindspore.cn/install/en#installation-verification
