### ISSUE TITLE
The value Parameter (name=0.gamma, shape=(512,), dtype=Float32, requires_grad=True) , its name '0.gamma' already exists. Please set a unique name for the parameter.

### ISSUE THREAD

**Issue by FEI120483** [mindspore-lab/mindcv#736]
If this is your first time, please read our contributor guidelines:
https://github.com/mindspore-lab/mindcv/blob/main/CONTRIBUTING.md

**Describe the bug/ 问题描述 (Mandatory / 必填)**
When I use Openi ( Cloudbrain Model Training Mission for my botnet model training). This problem happend.

- **Hardware Environment(`Ascend`/`GPU`/`CPU`)  / 硬件环境**: Ascend NPU
> Please delete the backend not involved / 请删除不涉及的后端: Ascend NPU
> /device ascend/GPU/CPU/kirin/等其他芯片

- **Software Environment / 软件环境 (Mandatory / 必填)**: 
-- MindSpore version (e.g., 1.7.0.Bxxx) :  1.10.1_train_for_naic
-- Python version (e.g., Python 3.7.5) : 3.7
-- OS platform and distribution (e.g., Linux Ubuntu 16.04):
-- GCC/Compiler version (if compiled from source):

- **Excute Mode / 执行模式 (Mandatory / 必填)(`PyNative`/`Graph`)**:
> Please delete the mode not involved / 请删除不涉及的模式:
> /mode pynative
> /mode graph

**To Reproduce / 重现步骤 (Mandatory / 必填)**
https://openi.pcl.ac.cn/zhengyifei/Project.git
1. Go to '...' Go to CloudBrain
2. Click on '....'  Training Mission ----> new training mission --->
![Uploading Screenshot 2023-09-25 at 23.49
<img width="1122" alt="Screenshot 2023-09-25 at 23 49 01" src="https://github.com/mindspore-lab/mindcv/assets/122851093/368db4c5-c3a3-4990-a526-f87c3d155cb7">
.01.png…]()
3. Scroll down to '....'  running and see error log

**Expected behavior / 预期结果 (Mandatory / 必填)**
Can training normally

**Screenshots/ 日志 / 截图 (Mandatory / 必填)**
<img width="1316" alt="Screenshot 2023-09-25 at 23 41 09" src="https://github.com/mindspore-lab/mindcv/assets/122851093/4f8e75b6-9139-4ab9-a3e5-758afe20a5d3">

**Additional context / 备注 (Optional / 选填)**

**Comment by geniuspatrick** [comment]
This doesn't seem to be a issue about mindcv, according to your latest repo
> https://openi.pcl.ac.cn/zhengyifei/Project/src/commit/f8d253b8d778ab145d4c3d03e85ba28edee27d26
