### ISSUE TITLE
安装 mindcv 时没报错, 但 import 时报错 No module named '_bz2' 请问如何解决

### ISSUE THREAD

**Issue by liyi93319** [mindspore-lab/mindcv#745]
环境: 鲲鹏920 + Ascend 910 + CentOS Linux release 7.9.2009 (AltArch) + python 3.7.5 + mindspore 2.1.0 
mindspore 可以正常在npu上跑训练, 安装 mindcv 时没报错, 但 import 时报错 No module named '_bz2' 请问如何解决?

![image](https://github.com/mindspore-lab/mindcv/assets/43629316/7820df8e-8f6a-4d57-a8b1-f578a76f0d2c)

**Comment by geniuspatrick** [comment]
Hi, `bz2` is a system module of Python.

> Probably as you built python from source, you don't have bz2 headers.

This [discussion](https://stackoverflow.com/questions/12806122/missing-python-bz2-module) may solve your problem.

BTW, It looks like you are using bare python. And we highly recommand using [conda](https://docs.conda.io/en/latest/).
