### ISSUE TITLE
在线评估，validate.py命令，指定ckpt权重文件参数错误

### ISSUE THREAD

**Issue by renjian-china** [mindspore-lab/mindcv#776]
If this is your first time, please read our contributor guidelines:
https://github.com/mindspore-lab/mindcv/blob/main/CONTRIBUTING.md

**Describe the bug/ 问题描述 (Mandatory / 必填)**
ckpt_path 需要指向具体的ckpt文件，帮助文档描述错误，如下：
![image](https://github.com/mindspore-lab/mindcv/assets/52620626/cb36e518-b124-40c2-b472-11a8f38e5447)

另外：ckpt_patch路径填写错误时，无错误信息提示，精度为0.001

- **Hardware Environment(`Ascend`/`GPU`/`CPU`)  / 硬件环境**:
> Please delete the backend not involved / 请删除不涉及的后端:
> /device ascend/GPU/CPU/kirin/等其他芯片

- **Software Environment / 软件环境 (Mandatory / 必填)**:
-- MindSpore version (e.g., 1.7.0.Bxxx) :
-- Python version (e.g., Python 3.7.5) :
-- OS platform and distribution (e.g., Linux Ubuntu 16.04):
-- GCC/Compiler version (if compiled from source):

- **Excute Mode / 执行模式 (Mandatory / 必填)(`PyNative`/`Graph`)**:
> Please delete the mode not involved / 请删除不涉及的模式:
> /mode pynative
> /mode graph

**To Reproduce / 重现步骤 (Mandatory / 必填)**

**Expected behavior / 预期结果 (Mandatory / 必填)**

**Screenshots/ 日志 / 截图 (Mandatory / 必填)**

**Additional context / 备注 (Optional / 选填)**

**Comment by IASZHT** [comment]
Thank you for your feedback. According to the description in the readme, we do hope users to modify and provide a specific ckpt path.

**Comment by IASZHT** [comment]
The problem of no warning for invalid ckpt path has been fixed. This issue is closed. If you have any questions, please reopen it and attach detailed information. We will continue to track it. Thank you for your contribution to mindcv.
